// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditMoviesController from "./edit_movies_controller.js"
application.register("edit-movies", EditMoviesController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SearchMoviesController from "./search_movies_controller.js"
application.register("search-movies", SearchMoviesController)
